name: jazzy_docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]
    
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: install jazzy
      run: gem install jazzy
    - name: build jazzy docs
      run: jazzy
    - name: pwd
      run: pwd
    - name: git br
      run: git branch
    - name: git st
      run: git status
      
      
      
